spring:
  application:
    name: inventory

server.port: 9091

eureka:
  client:
    initialInstanceInfoReplicationIntervalSeconds : 2
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
